class SenderArea < ActiveHash::Base
  self.data = [
    { id: 1, sender_area: '---' },
    { id: 2, sender_area: '北海道' },
    { id: 3, sender_area: '青森県' },
    { id: 4, sender_area: '岩手県' },
    { id: 5, sender_area: '宮城県' },
    { id: 6, sender_area: '秋田県' },
    { id: 7, sender_area: '山形県' },
    { id: 8, sender_area: '福島県' },
    { id: 9, sender_area: '茨城県' },
    { id: 10, sender_area: '栃木県' },
    { id: 11, sender_area: '群馬県' },
    { id: 12, sender_area: '埼玉県' },
    { id: 13, sender_area: '千葉県' },
    { id: 14, sender_area: '東京都' },
    { id: 15, sender_area: '神奈川県' },
    { id: 16, sender_area: '新潟県' },
    { id: 17, sender_area: '富山県' },
    { id: 18, sender_area: '石川県' },
    { id: 19, sender_area: '福井県' },
    { id: 20, sender_area: '山梨県' },
    { id: 21, sender_area: '長野県' },
    { id: 22, sender_area: '岐阜県' },
    { id: 23, sender_area: '静岡県' },
    { id: 24, sender_area: '愛知県' },
    { id: 25, sender_area: '三重県' },
    { id: 26, sender_area: '滋賀県' },
    { id: 27, sender_area: '京都府' },
    { id: 28, sender_area: '大阪府' },
    { id: 29, sender_area: '兵庫県' },
    { id: 30, sender_area: '奈良県' },
    { id: 31, sender_area: '和歌山県' },
    { id: 32, sender_area: '鳥取県' },
    { id: 33, sender_area: '島根県' },
    { id: 34, sender_area: '岡山県' },
    { id: 35, sender_area: '広島県' },
    { id: 36, sender_area: '山口県' },
    { id: 37, sender_area: '徳島県' },
    { id: 38, sender_area: '香川県' },
    { id: 39, sender_area: '愛媛県' },
    { id: 40, sender_area: '高知県' },
    { id: 41, sender_area: '福岡県' },
    { id: 42, sender_area: '佐賀県' },
    { id: 43, sender_area: '長崎県' },
    { id: 44, sender_area: '熊本県' },
    { id: 45, sender_area: '大分県' },
    { id: 46, sender_area: '宮崎県' },
    { id: 47, sender_area: '鹿児島県' },
    { id: 48, sender_area: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :items
end
